# Generated by Django 3.1 on 2020-08-22 15:37

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Katagoriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, max_length=200)),
                ('ikon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maddeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='<small>Kelepir internetten bulunduysa şurda websiteyi palşın</small>', null=True)),
                ('satici', models.CharField(blank=True, max_length=200)),
                ('fiyat', models.DecimalField(decimal_places=2, help_text='İndirimi fıyat', max_digits=8, verbose_name='Fıyat')),
                ('orjinalFiyat', models.DecimalField(blank=True, decimal_places=2, help_text='Orjinal fıyat', max_digits=8, null=True, verbose_name='orjinal Fıyatı')),
                ('kargo', models.BooleanField(help_text='Kargo ücretsizse burayı tıklayın')),
                ('kupon', models.CharField(blank=True, help_text='Bildirmek istediğiniz kupon varsa, buraya yazın', max_length=100, null=True)),
                ('baslik', models.CharField(help_text='Kısa bir tanımlayıcı başlık', max_length=300, verbose_name='Başlık')),
                ('ayrintilar', ckeditor.fields.RichTextField(help_text='Kelepiri kendi sözlerinizle anlatın ve neden kaçılmaz fırsat olduğunu başkalarına açıklayın.', max_length=1000, verbose_name='Detaylı ayrıntılar')),
                ('goruntu', models.ImageField(blank=True, default='madde_goruntuleri/shopping.jpg', help_text='bir resim yüklemek, başkalarının anlaşmayı daha iyi anlamasına yardımcı olur', null=True, upload_to='madde_goruntuleri', verbose_name='Görüntü')),
                ('bas_tarih', models.DateField(blank=True, null=True, verbose_name='İndirimin Başlangıç Tarihi')),
                ('son_tarih', models.DateField(blank=True, null=True, verbose_name='İndirimin bitme tarihi')),
                ('online', models.BooleanField(help_text='Yerel fırsat (mağazada / çevrimdışı)')),
                ('diyar', models.CharField(blank=True, max_length=100, null=True)),
                ('derece', models.IntegerField(blank=True, default=0, null=True)),
                ('duyurmaTarihi', models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 22, 15, 37, 35, 215740, tzinfo=utc))),
                ('kaynamavakti', models.DateTimeField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('oylar', models.IntegerField(blank=True, default=0, null=True)),
                ('w3w', models.CharField(blank=True, help_text='<a href="https://what3words.com/susma.hurma.e%C5%9Fyal%C4%B1"><small>Yardım ve örnek için şurayı tıklayın</small></a>', max_length=100, null=True, verbose_name='What3Words')),
                ('bookmarked', models.ManyToManyField(blank=True, default=None, related_name='bookmarked', to=settings.AUTH_USER_MODEL)),
                ('katagori', models.ManyToManyField(to='madde.Katagoriler')),
                ('oyveren', models.ManyToManyField(blank=True, related_name='collected_votes', to=settings.AUTH_USER_MODEL)),
                ('paylasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tukenmiscagiri', models.ManyToManyField(blank=True, default=None, related_name='expired_call', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('madde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madde.maddeler')),
            ],
        ),
        migrations.CreateModel(
            name='Commentlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comment', to='madde.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='madde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='madde.maddeler'),
        ),
    ]
