# Generated by Django 3.0.8 on 2020-07-29 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0001_initial'),
        ('madde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maddeler',
            name='derece',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maddeler',
            name='kaynamavakti',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='maddeler',
            name='oylar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maddeler',
            name='paylasan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hesaplar.Kullanici'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesaplar.Kullanici')),
                ('madde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madde.Maddeler')),
            ],
        ),
    ]
