# Generated by Django 3.1 on 2020-08-22 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='derece',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
