# Generated by Django 4.1.7 on 2023-03-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='guncelenmisTarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
