# Generated by Django 3.1 on 2020-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0002_auto_20200822_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, help_text='İndirimli fıyat', max_digits=8, verbose_name='Fıyat'),
        ),
    ]
