# Generated by Django 3.1 on 2020-08-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0003_auto_20200822_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='kargo',
            field=models.BooleanField(help_text='Kargo ücretsizse burayı tıklayın', null=True),
        ),
    ]
