# Generated by Django 3.0.8 on 2020-07-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0003_auto_20200729_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
