# Generated by Django 3.0.8 on 2020-07-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0004_auto_20200729_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='bas_tarih',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='baslik',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='diyar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='kargo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='kupon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='son_tarih',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
