# Generated by Django 3.1 on 2020-08-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0004_auto_20200822_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='oy',
            field=models.BooleanField(default=None),
        ),
    ]
