# Generated by Django 3.1 on 2020-08-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0005_votes_oy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='oy',
            field=models.BooleanField(default=True),
        ),
    ]
