# Generated by Django 3.0.8 on 2020-07-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0005_auto_20200729_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='bas_tarih',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='son_tarih',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
