# Generated by Django 3.0.8 on 2020-07-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0006_auto_20200729_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='kaynamavakti',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
