# Generated by Django 3.0.8 on 2020-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0007_auto_20200729_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='orjinalFiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
