# Generated by Django 3.0.8 on 2020-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0008_maddeler_orjinalfiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='goruntu',
            field=models.ImageField(blank=True, default='shopping.jpg', null=True, upload_to='madde_goruntuleri'),
        ),
    ]
