# Generated by Django 3.1 on 2020-08-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0008_delete_customcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
