# Generated by Django 3.1 on 2020-09-12 14:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madde', '0009_maddeler_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, help_text='İndirimli fıyat', max_digits=8),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='orjinalFiyat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orjinal fiyat', max_digits=8, null=True, verbose_name='orjinal Fiyatı'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='url',
            field=models.URLField(blank=True, help_text='<small>Kelepir internetten bulunduysa şurda websiteyi paylaşın</small>', null=True),
        ),
        migrations.CreateModel(
            name='Kuponlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='<small>Kelepir internetten bulunduysa şurda websiteyi palşın</small>', null=True)),
                ('satici', models.CharField(blank=True, max_length=200)),
                ('kupon', models.CharField(blank=True, help_text='Bildirmek istediğiniz kupon varsa, buraya yazın', max_length=100)),
                ('kuponCesiti', models.CharField(choices=[('YE', '% İndirim'), ('Tİ', '<span class="fas fa-lira-sign"></span> İndirimi'), ('BK', 'Bedava Kargo')], max_length=50, null=True, verbose_name='Küpon çeşiti')),
                ('baslik', models.CharField(help_text='Kısa bir tanımlayıcı başlık', max_length=300, verbose_name='Başlık')),
                ('ayrintilar', ckeditor.fields.RichTextField(help_text='Kelepiri kendi sözlerinizle anlatın ve neden kaçılmaz fırsat olduğunu başkalarına açıklayın.', verbose_name='Detaylı ayrıntılar')),
                ('bas_tarih', models.DateField(blank=True, null=True, verbose_name='İndirimin Başlangıç Tarihi')),
                ('son_tarih', models.DateField(blank=True, null=True, verbose_name='İndirimin bitme tarihi')),
                ('duyurmaTarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('derece', models.IntegerField(blank=True, default='0', null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('oylar', models.IntegerField(blank=True, default=0, null=True)),
                ('allow_comments', models.BooleanField(default=True, verbose_name='allow comments')),
                ('bookmarked', models.ManyToManyField(blank=True, default=None, related_name='bookmarked_coupons', to=settings.AUTH_USER_MODEL)),
                ('oyveren', models.ManyToManyField(blank=True, related_name='collected_votes_coupons', to=settings.AUTH_USER_MODEL)),
                ('paylasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tukenmiscagiri', models.ManyToManyField(blank=True, default=None, related_name='expired_call_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
