# Generated by Django 3.0.8 on 2020-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0009_maddeler_goruntu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='goruntu',
            field=models.ImageField(blank=True, default='images/shopping.jpg', null=True, upload_to='madde_goruntuleri'),
        ),
    ]
