# Generated by Django 3.1 on 2020-09-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0010_auto_20200912_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuponlar',
            name='goruntu',
            field=models.ImageField(blank=True, default='madde_goruntuleri/shopping.jpg', help_text='bir resim yüklemek, başkalarının anlaşmayı daha iyi anlamasına yardımcı olur', null=True, upload_to='kupon_goruntuleri', verbose_name='Görüntü'),
        ),
    ]
