# Generated by Django 3.0.8 on 2020-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0010_auto_20200730_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='goruntu',
            field=models.ImageField(blank=True, default='madde_goruntuleri/shopping.jpg', null=True, upload_to='madde_goruntuleri'),
        ),
    ]
