# Generated by Django 3.1 on 2020-09-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0011_kuponlar_goruntu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuponlar',
            name='tukenmisSayi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='maddeler',
            name='tukenmisSayi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
