# Generated by Django 3.0.8 on 2020-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0011_auto_20200730_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='w3w',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
