# Generated by Django 3.0.8 on 2020-08-02 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0012_maddeler_w3w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
