# Generated by Django 3.0.8 on 2020-08-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0013_auto_20200802_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='ayrintilar',
            field=models.TextField(help_text='Kelepiri kendi sözlerinizle anlatın ve neden kaçılmaz fırsat olduğunu başkalarına açıklayın.', verbose_name='Detaylı ayrıntılar'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='bas_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='İndirimin Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='baslik',
            field=models.CharField(help_text='Kısa bir tanımlayıcı başlık', max_length=300, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, help_text='İndirimi fıyat', max_digits=5, verbose_name='Fıyat'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='goruntu',
            field=models.ImageField(blank=True, default='madde_goruntuleri/shopping.jpg', help_text='bir resim yüklemek, başkalarının anlaşmayı daha iyi anlamasına yardımcı olur', null=True, upload_to='madde_goruntuleri', verbose_name='Görüntü'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='kargo',
            field=models.BooleanField(help_text='Kargo ücretsizse burayı tıklayın'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='katagori',
            field=models.CharField(choices=[('Elektronik', 'Elektronik'), ('Moda ve aksesuarlar', 'Moda ve aksesuarlar'), ('Bahçe ve DIY', 'Bahçe ve DIY'), ('Kültür ve boş zaman', 'Kültür ve boş zaman'), ('bakkal alışveriş', 'bakkal alışveriş'), ('Oyun', 'Oyun')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='kupon',
            field=models.CharField(blank=True, help_text='Bildirmek istediğiniz kupon varsa, buraya yazın', max_length=100),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='online',
            field=models.BooleanField(help_text='Yerel fırsat (mağazada / çevrimdışı)'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='orjinalFiyat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orjinal fıyat', max_digits=5, null=True, verbose_name='orjinal Fıyatı'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='son_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='İndirimin bitme tarihi'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='url',
            field=models.URLField(blank=True, help_text='Kelepir internetten bulunduysa şurda websiteyi palşın', null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='w3w',
            field=models.CharField(blank=True, max_length=100, verbose_name='What3Words'),
        ),
    ]
