# Generated by Django 3.0.8 on 2020-08-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0015_auto_20200803_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katagoriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, max_length=200)),
                ('ikon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='maddeler',
            name='katagori',
        ),
        migrations.AddField(
            model_name='maddeler',
            name='katagori',
            field=models.ManyToManyField(to='madde.Katagoriler'),
        ),
    ]
