# Generated by Django 3.0.8 on 2020-08-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0002_auto_20200729_2155'),
        ('madde', '0016_auto_20200806_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hesaplar.Kullanici')),
                ('madde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='madde.Maddeler')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
