# Generated by Django 3.0.8 on 2020-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='ayrintilar',
            field=models.CharField(help_text='Kelepiri kendi sözlerinizle anlatın ve neden kaçılmaz fırsat olduğunu başkalarına açıklayın.', max_length=1000, verbose_name='Detaylı ayrıntılar'),
        ),
    ]
