# Generated by Django 3.1 on 2020-08-07 17:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0018_auto_20200807_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='ayrintilar',
            field=ckeditor.fields.RichTextField(help_text='Kelepiri kendi sözlerinizle anlatın ve neden kaçılmaz fırsat olduğunu başkalarına açıklayın.', max_length=1000, verbose_name='Detaylı ayrıntılar'),
        ),
    ]
