# Generated by Django 3.1 on 2020-08-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0002_auto_20200729_2155'),
        ('madde', '0019_auto_20200807_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='hesaplar.Kullanici'),
        ),
    ]
