# Generated by Django 3.1 on 2020-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0002_auto_20200729_2155'),
        ('madde', '0020_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='hesaplar.Kullanici'),
        ),
    ]
