# Generated by Django 3.1 on 2020-08-12 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madde', '0022_auto_20200808_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='oyveren',
            field=models.ManyToManyField(blank=True, related_name='collected_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='commentlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_comment', to='madde.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
