# Generated by Django 3.1 on 2020-08-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0023_auto_20200812_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='liked_date',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
    ]
