# Generated by Django 3.1 on 2020-08-18 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madde', '0024_auto_20200817_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maddeler',
            name='slug',
            field=models.SlugField(default=2, max_length=250, unique_for_date='duyurmaTarihi'),
            preserve_default=False,
        ),
    ]
