# Generated by Django 3.1 on 2020-08-19 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madde', '0025_auto_20200818_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='maddeler',
            name='tukenmiscagiri',
            field=models.ManyToManyField(blank=True, default=None, related_name='expired_call', to=settings.AUTH_USER_MODEL),
        ),
    ]
