# Generated by Django 3.1 on 2020-08-20 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madde', '0026_maddeler_tukenmiscagiri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maddeler',
            name='slug',
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='derece',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='diyar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='kupon',
            field=models.CharField(blank=True, help_text='Bildirmek istediğiniz kupon varsa, buraya yazın', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='oylar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='w3w',
            field=models.CharField(blank=True, help_text='<a href="https://what3words.com/susma.hurma.e%C5%9Fyal%C4%B1"><small>Yardım ve örnek için şurayı tıklayın</small></a>', max_length=100, null=True, verbose_name='What3Words'),
        ),
    ]
