# Generated by Django 3.1 on 2020-08-22 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0027_auto_20200820_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 22, 12, 23, 52, 194857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, help_text='İndirimi fıyat', max_digits=8, verbose_name='Fıyat'),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='orjinalFiyat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orjinal fıyat', max_digits=8, null=True, verbose_name='orjinal Fıyatı'),
        ),
    ]
