# Generated by Django 3.1 on 2020-08-22 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('madde', '0028_auto_20200822_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 22, 12, 34, 38, 423300, tzinfo=utc)),
        ),
    ]
