# Generated by Django 3.1 on 2020-08-22 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madde', '0030_auto_20200822_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddeler',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maddeler',
            name='duyurmaTarihi',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 8, 22, 12, 36, 15, 343066, tzinfo=utc)),
        ),
    ]
