# Generated by Django 3.0.8 on 2020-07-29 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paylasimlar', models.IntegerField()),
                ('yorumlar', models.IntegerField()),
                ('ensicak', models.IntegerField()),
                ('takipciler', models.IntegerField()),
                ('sehir', models.CharField(max_length=200)),
                ('Kullanici', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
