# Generated by Django 3.1.14 on 2023-04-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
