# Generated by Django 4.1.7 on 2023-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0002_auto_20230401_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
