# Generated by Django 3.1 on 2020-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0002_auto_20200729_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='dogum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
