# Generated by Django 3.1 on 2020-08-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0003_auto_20200808_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='resim',
            field=models.ImageField(blank=True, default='profiler/profile.png', null=True, upload_to='profiler'),
        ),
    ]
