# Generated by Django 3.1 on 2020-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0004_auto_20200808_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='insta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
