# Generated by Django 3.1 on 2020-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesaplar', '0005_kullanici_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='ensicak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='paylasimlar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='takipciler',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='yorumlar',
            field=models.IntegerField(default=0),
        ),
    ]
